kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: "127.0.0.1"  # Change this to your EC2 private IP (run "hostname -I" to check or from your EC2 dashboard)
  apiServerPort: 33894  # should be different from `argocd-cluster` port
nodes:
  - role: control-plane
    image: kindest/node:v1.33.1